# This file was generated by GoReleaser. DO NOT EDIT.
cask "rolemux" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "d52ac65f86361e4e8b8705966fb47a1604c4e6cd30c3c630ed53ffa46ccc61cb"
      url "https://github.com/basant-kumar/rolemux/releases/download/v#{version}/rolemux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dcb2f0b160888da731788a0030ad8272f9774a1db1cfa5f35c17efd708618eab"
      url "https://github.com/basant-kumar/rolemux/releases/download/v#{version}/rolemux_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rolemux"
  desc "Use the right AI model for planning, implementation, and review"
  homepage "https://github.com/basant-kumar/rolemux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rolemux"

  # No zap stanza required

  caveats <<~EOS
    Run `rolemux install --global --hosts all` and `rolemux doctor --json` after installation.
  EOS
end
