# This file was generated by GoReleaser. DO NOT EDIT.
cask "rolemux" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "6347c801b88846844293b3b9ee016a908504e8414f8ad4ae95ea1e99836c5ae5"
      url "https://github.com/basant-kumar/rolemux/releases/download/v#{version}/rolemux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "83059a7e2414210fe2d6af7110b7077a0595a3e76f2142b7b5807ed5df349401"
      url "https://github.com/basant-kumar/rolemux/releases/download/v#{version}/rolemux_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rolemux"
  desc "Use the right AI model for planning, implementation, and review"
  homepage "https://github.com/basant-kumar/rolemux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rolemux"

  # No zap stanza required

  caveats <<~EOS
    Run `rolemux install --global --hosts all` and `rolemux doctor --json` after installation.
  EOS
end
