# This file was generated by GoReleaser. DO NOT EDIT.
cask "rolemux" do
  depends_on :macos

  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "1f3ce4e4b9e376f0f7bb2134cdb0c23a37a2cae7a867376328a2ed46028cfc02"
      url "https://github.com/basant-kumar/rolemux/releases/download/v#{version}/rolemux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d88848ff15fc4e8fd3e62a2900d50739c97ea7459cdb8d8b81c32d37974b2294"
      url "https://github.com/basant-kumar/rolemux/releases/download/v#{version}/rolemux_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "rolemux"
  desc "Use the right AI model for planning, implementation, and review"
  homepage "https://github.com/basant-kumar/rolemux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rolemux"

  # No zap stanza required

  caveats <<~EOS
    Run `rolemux install --global --hosts all` and `rolemux doctor --json` after installation.
  EOS
end
